Improve expandable table
ColorlibHQ/AdminLTE pull request #3458
Opened 2021-02-27 11:45 UTC by hkvstore

2021-02-27 11:51 UTC, danny007in commented
do not add dist/compiled
check https://github.com/ColorlibHQ/AdminLTE#contributing

2021-02-27 11:53 UTC, danny007in commented
explane whats use of this PR in visually or by code

2021-02-27 12:01 UTC, danny007in requested changes

2021-02-27 12:01 UTC, danny007in commented on build/scss/_table.scss
> +    td i.expandable-table-caret {
issue may be for child `td > i`

2021-02-27 12:01 UTC, danny007in commented on pages/tables/simple.html
> +                        <i class="expandable-table-caret fas fa-caret-right fa-fw"></i>
y extra `expandable-table-caret`
and 
plz explain whats use of this PR

2021-02-27 12:02 UTC, hkvstore commented on build/scss/_table.scss
> +    td i.expandable-table-caret {
The icon may not be directly under ``td``.

2021-02-27 12:04 UTC, hkvstore commented on pages/tables/simple.html
> +                        <i class="expandable-table-caret fas fa-caret-right fa-fw"></i>
There may be other icons in the expandable row, they will also be affected by the CSS if just ``td > i`` or ``td i`` is used.

2021-02-27 12:06 UTC, danny007in commented on build/scss/_table.scss
> +    td i.expandable-table-caret {
is there
any conflict by 
changing
`td i.expandable-table-caret`
to
`td > i.expandable-table-caret`

2021-02-27 12:11 UTC, hkvstore commented on build/scss/_table.scss
> +    td i.expandable-table-caret {
> The icon may not be directly

2021-02-27 12:19 UTC, hkvstore commented on build/js/ExpandableTable.js
> +const SELECTOR_BODY = '.expandable-body'
ee740e97e49028405478376cad8e4e27ffdfe06a

2021-02-27 12:19 UTC, danny007in commented on build/scss/_table.scss
> +    td i.expandable-table-caret {
add extra example in html for

- The icon may not be directly under td.

2021-02-27 12:44 UTC, hkvstore commented on build/scss/_table.scss
> +    td i.expandable-table-caret {
daa448d4df99a99680083f9c5e6591f1add96914

2021-02-27 13:11 UTC, danny007in approved these changes

2021-02-27 13:16 UTC, danny007in commented
@hkvstore i have approved it lets, wait for any other's to take closer review 👍🏼

2021-02-27 13:53 UTC, REJack commented
I will check it later

2021-02-28 17:43 UTC, REJack commented on pages/tables/simple.html
> +                                  <button type="button" class="btn btn-primary p-0">
Is this intended to be a button?

2021-02-28 18:14 UTC, danny007in commented on pages/tables/simple.html
> +                                  <button type="button" class="btn btn-primary p-0">
Yes, @hkvstore 's concept is that only we can add custom button or any element.
And sorry for ignoring that example we needs to add separate example for that.

2021-02-28 18:16 UTC, danny007in commented on pages/tables/simple.html
> +                                  <button type="button" class="btn btn-primary p-0">
Also only custom add class gets target not all icons in row

2021-02-28 18:18 UTC, danny007in commented on pages/tables/simple.html
> +                                  <button type="button" class="btn btn-primary p-0">
@hkvstore can u add completely separate example below, instead of editing

2021-02-28 19:57 UTC, REJack commented on pages/tables/simple.html
> +                                  <button type="button" class="btn btn-primary p-0">
there is a example above as a simple icon ^^ but then it's OK :D I will merge it, it works like it should :P

2021-02-28 19:58 UTC, merged