add errorhandling to cardrefresh plugin
ColorlibHQ/AdminLTE pull request #3555
Opened 2021-03-31 07:37 UTC by equada

Currently, if a server error occurs while loading contents in the card-refresh plugin, the overlay just stays and the spinner turns forever. With this change, the overlay will be hidden if an error occurs and there is an error handler function in the settings

2021-03-31 07:48 UTC, danny007in commented
resolve js-lint 🕵🏼

2021-03-31 10:46 UTC, equada commented
@danny007in

The html:
```html
<div class="card">
     <div class="card-header">
       <h5 class="card-title">This is a title</h5>
       <button type="button" class="btn btn-primary btn-sm float-right" data-card-widget="card-refresh" data-source="/public/ajax/route"><i class="fas fa-redo"></i> refresh</button>
     </div>
     <div class="card-body">

     </div>
</div>
```
When opening the page, the card starts loading:
![image](https://user-images.githubusercontent.com/81673782/113131639-c0b92c80-921d-11eb-8d19-e70d458c8b12.png)

Then, if for example an error occurs on the server-side (the route `/public/ajax/route`), or basically if the jquery ajax `$.get` request fails in any way, the card is still loading, the overlay stays, eventhough the request is already finished (failed) in the background:

![image](https://user-images.githubusercontent.com/81673782/113132343-9fa50b80-921e-11eb-9a11-68393931ca95.png)

The user gets no feedback that something went wrong and the button is behind the overlay. (I know this could be fixed with css z-index but thats not the point).

My fix hides the overlay if something went wrong and gives the developer the opportunity to implement a proper error-handling, which is currently not possible at all

2021-03-31 10:53 UTC, danny007in commented
Along with this,
 add background gray to red,
Which represents - Something went wrong.

2021-03-31 11:12 UTC, equada commented
@danny007in I'm not quite sure what you mean by this. Sure, the user should get a feedback in some form like I mentioned, but if something went wrong,  the overlay is now hidden to reveal the button (so I cant color the overlay red)

Coloring any other component of the card red, like the card, card-header, card-body or button seems invasive. The Developer should not fear that admin-lte randomly colors something red or gives classes to elements.

My suggestion would be to clear the card-body and put the `errorThrown` inside it, like this:
```js
this._parent.find(this._settings.content).html('<span class="text-danger">'+errorThrown+'</span>')
```

![image](https://user-images.githubusercontent.com/81673782/113135510-7e461e80-9222-11eb-8186-936f2cfb6311.png)

Would that be fine?

2021-03-31 21:53 UTC, danny007in requested changes

2021-03-31 21:53 UTC, danny007in commented on build/js/CardRefresh.js
> +      this._settings.onLoadFail.call($(this), jqXHR, textStatus, errorThrown)
why `onLoadFail`.
`.fail` is enough

2021-03-31 21:53 UTC, danny007in commented on build/js/CardRefresh.js
> +    }, this._settings.responseType !== '' && this._settings.responseType).fail((jqXHR, textStatus, errorThrown) => {
`,fail` nextliine

2021-03-31 21:53 UTC, danny007in commented on build/js/CardRefresh.js
> +      this._parent.find(this._settings.content).empty().append(msg)
try to make single line

2021-03-31 22:00 UTC, danny007in commented on build/js/CardRefresh.js
> +    }, this._settings.responseType !== '' && this._settings.responseType).fail((jqXHR, textStatus, errorThrown) => {
also add `.done`

2021-03-31 22:05 UTC, danny007in commented on build/js/CardRefresh.js
> +      const msg = $(this.__settings.errorTemplate).text(errorThrown)
`__settings` to `_settings`

2021-04-01 10:52 UTC, equada commented on build/js/CardRefresh.js
> +      this._settings.onLoadFail.call($(this), jqXHR, textStatus, errorThrown)
because the other event functions are called `onLoadStart` and `onLoadDone` so it seemed logical to me to call it `onLoadFail` ?

2021-04-02 01:39 UTC, danny007in commented on build/js/CardRefresh.js
> +      this._settings.onLoadFail.call($(this), jqXHR, textStatus, errorThrown)
remove on 0nLoadFail because by default its reponse is same.
but not as loadStart or loadDone.

2021-04-25 15:24 UTC, REJack commented
@danny007in is this ready to merge too?

2021-04-25 17:26 UTC, danny007in requested changes

2021-04-25 17:26 UTC, danny007in commented on build/js/CardRefresh.js
> +      this._settings.onLoadFail.call($(this), jqXHR, textStatus, errorThrown)
@REJack does onLoadFail is required or not

2021-04-25 17:26 UTC, danny007in commented on build/js/CardRefresh.js
> +  errorTemplate: '<span class="text-danger"></span>',
add
`showErrorTemplate: true`

2021-04-25 17:26 UTC, danny007in commented on build/js/CardRefresh.js
> +  errorTemplate: '<span class="text-danger"></span>',
add docs to it

2021-04-25 17:26 UTC, danny007in commented on build/js/CardRefresh.js
> +      const msg = $(this._settings.errorTemplate).text(errorThrown)
if statement `showErrorTemplate`

2021-04-25 19:49 UTC, REJack commented on build/js/CardRefresh.js
> +      this._settings.onLoadFail.call($(this), jqXHR, textStatus, errorThrown)
I would stay with it, then you can trigger alerts or something else with this.

2021-04-27 12:02 UTC, danny007in approved these changes

2021-04-27 12:03 UTC, merged

2021-04-27 12:19 UTC, equada commented
@danny007in Thank you for completing the requested changes!