feat: light mode only alt css
ColorlibHQ/AdminLTE pull request #3595
Opened 2021-04-13 12:28 UTC by danny007in

Fixed https://github.com/ColorlibHQ/AdminLTE/issues/3530

2021-04-13 21:10 UTC, REJack requested changes

2021-04-13 21:10 UTC, REJack commented on build/scss/mixins/_accent.scss
> +    .accent-#{$name} {
this should be `&.accent-#{$name} {` or not?

2021-04-14 05:28 UTC, danny007in commented on build/scss/mixins/_accent.scss
> +    .accent-#{$name} {
result will be same 😃

2021-04-14 13:10 UTC, danny007in commented on build/scss/mixins/_accent.scss
> +    .accent-#{$name} {
once will check

2021-04-15 12:24 UTC, danny007in commented on build/scss/mixins/_accent.scss
> +    .accent-#{$name} {
FIxed

2021-04-25 13:00 UTC, danny007in commented
jack 
edit this pr like bundlewatch
then merge

2021-04-25 15:24 UTC, REJack approved these changes

2021-04-25 15:24 UTC, merged