Fix icon change when enter/exit full screen mode
ColorlibHQ/AdminLTE pull request #3639
Opened 2021-04-28 21:20 UTC by Shidersz

Fix full screen icon change when exit the full screen mode using the **ESC** key. Related issue: #3638 
These changes implement detection of full screen events in order to toggle the icon of the full screen button. This way we can ensure the icon is always the right one.

**IMPORTANT:** Note this won't impact when entering/exiting the full screen mode using the **F11** key. There is no current workaround for this one, you can read more about this situation on next link:
https://stackoverflow.com/questions/43392583/fullscreen-api-not-working-if-triggered-with-f11

2021-04-29 09:13 UTC, danny007in approved these changes

2021-04-29 09:23 UTC, danny007in commented
click not working in sidebar submenu check https://deploy-preview-3639--colorlibhq-adminlte.netlify.app/

2021-04-29 09:30 UTC, danny007in requested changes
click not working in sidebar submenu check https://deploy-preview-3639--colorlibhq-adminlte.netlify.app/

2021-04-29 13:34 UTC, Shidersz commented
@danny007in I don't believe that problem is related to these changes. This issue already happen to me while testing on my local environment previously to this PR. Maybe @REJack know what can be the cause of this... So I can solve it on my local environment too.

2021-04-29 17:20 UTC, Shidersz commented
@danny007in  @REJack I can confirm that commenting some code of the `Iframe.js` file makes the sidebar links works on my local environment. I'm not sure what is the purpose of that file, but it is not related to the changes provided in this PR. You can see the changes on next `git diff` output.

```diff
diff --git a/build/js/IFrame.js b/build/js/IFrame.js
index 0fbb2472..596fdded 100644
--- a/build/js/IFrame.js
+++ b/build/js/IFrame.js
@@ -32,7 +32,7 @@ const SELECTOR_TAB_EMPTY = `${SELECTOR_TAB_CONTENT} .tab-empty`
 const SELECTOR_TAB_LOADING = `${SELECTOR_TAB_CONTENT} .tab-loading`
 const SELECTOR_TAB_PANE = `${SELECTOR_TAB_CONTENT} .tab-pane`
 const SELECTOR_SIDEBAR_MENU_ITEM = '.main-sidebar .nav-item > a.nav-link'
-const SELECTOR_SIDEBAR_SEARCH_ITEM = '.sidebar-search-results .list-group-item'
+// const SELECTOR_SIDEBAR_SEARCH_ITEM = '.sidebar-search-results .list-group-item'
 const SELECTOR_HEADER_MENU_ITEM = '.main-header .nav-item a.nav-link'
 const SELECTOR_HEADER_DROPDOWN_ITEM = '.main-header a.dropdown-item'
 const CLASS_NAME_IFRAME_MODE = 'iframe-mode'
@@ -254,10 +254,12 @@ class IFrame {
         this._fixHeight()
       }, 1)
     })
+    /*
     $(document).on('click', `${SELECTOR_SIDEBAR_MENU_ITEM}, ${SELECTOR_SIDEBAR_SEARCH_ITEM}`, e => {
       e.preventDefault()
       this.openTabSidebar(e.target)
     })
+    */
```

2021-04-29 18:17 UTC, danny007in commented
Probably by this https://github.com/ColorlibHQ/AdminLTE/pull/3605

2021-04-29 18:36 UTC, Shidersz commented
@danny007in That one just touched the style of the sidebar search item, I can't imagine how that PR can mess all the link items. Also, I remember I have experience the issue when installing my development environment, before making any changes.

2021-05-01 08:00 UTC, danny007in commented
> 
> 
> @danny007in That one just touched the style of the sidebar search item, I can't imagine how that PR can mess all the link items. Also, I remember I have experience the issue when installing my development environment, before making any changes. IMO the bug comes from the next commit:
> 
> [5b07bdd](https://github.com/ColorlibHQ/AdminLTE/commit/5b07bdd8e9c6710f0b5208dfedf265c418af5b57)
> 
> If you check it, you can see the `_setupListeners()` function was moved from `_initFrameElement()` to `init()`. The `_setupListeners()` is the one that actually registers the click event listener with the `e.preventDefault()` on the sidebar links.

@Shidersz if u r sure, plz raise an separate issue on _setupListeners()

2021-05-01 13:52 UTC, Shidersz commented
@danny007in I prefer @REJack review it, since he have more knowledge about this package. I will make an issue later explaining the problem if not solved soon...

2021-05-01 14:06 UTC, danny007in approved these changes

2021-05-01 14:06 UTC, merged