Fix disabled style for some buttons.
ColorlibHQ/AdminLTE pull request #3696
Opened 2021-05-15 19:12 UTC by Shidersz

Currently, when hover on some buttons (`btn-default` or buttons with `bg-gradient-*` classes) the hover effect is enabled. Those effects are not enabled for the other buttons (`btn-primary`, `btn-info`, etc.). Check next videos for an example:

**Hover effect on `.btn-default`**:

https://user-images.githubusercontent.com/63609705/118375333-75719800-b597-11eb-9324-0e9410fba0b1.mp4

**Hover effect on `.btn.bg-gradient-*`**:

https://user-images.githubusercontent.com/63609705/118375330-71de1100-b597-11eb-86c2-057664bf279e.mp4

This PR removes the hover effect from the mentioned buttons to match the behaviour present for most of the buttons. Check next videos for the result of applying this PR:

**NO hover effect on `.btn-default`**:

https://user-images.githubusercontent.com/63609705/118375332-730f3e00-b597-11eb-988c-c0e63133da47.mp4

**NO hover effect on `.btn.bg-gradient-*`**:

https://user-images.githubusercontent.com/63609705/118375325-6f7bb700-b597-11eb-8a75-2d9ab7be141b.mp4

2021-05-15 21:40 UTC, danny007in requested changes

2021-05-15 21:40 UTC, danny007in commented on build/scss/mixins/_backgrounds.scss
> +        background: $color linear-gradient(180deg, mix($body-bg, $color, 15%), $color) repeat-x !important;
gradient effect no needed,
because of feasible issue

2021-05-15 21:40 UTC, danny007in commented on build/scss/mixins/_backgrounds.scss
> +        color: color-yiq($color);
`color: color-yiq($color);` not required

2021-05-16 01:08 UTC, Shidersz commented on build/scss/mixins/_backgrounds.scss
> +        color: color-yiq($color);
Actually, both changes are needed to fix the mentioned problem. Because I need the **disabled** state to overwrite the **color** and **background color** that the element gets from the `hover` effect. The values are the ones used on the button's normal state, take a look:

```scss
// Background Gradient Variant
@mixin background-gradient-variant($name, $color) {
  .bg-gradient-#{$name} {
    background: $color linear-gradient(180deg, mix($body-bg, $color, 15%), $color) repeat-x !important;
    color: color-yiq($color);

    &.btn {
      &:not(:disabled):not(.disabled):active,
      &:not(:disabled):not(.disabled).active,
      .show > &.dropdown-toggle {
        background-image: none !important;
      }

      &:hover {
        background: $color linear-gradient(180deg, mix($body-bg, darken($color, 7.5%), 15%), darken($color, 7.5%)) repeat-x !important;
        border-color: darken($color, 10%);
        color: darken(color-yiq($color), 7.5%);
      }

      &:not(:disabled):not(.disabled):active,
      &:not(:disabled):not(.disabled).active,
      &:active,
      &.active {
        background: $color linear-gradient(180deg, mix($body-bg, darken($color, 10%), 15%), darken($color, 10%)) repeat-x !important;
        border-color: darken($color, 12.5%);
        color: color-yiq(darken($color, 10%));
      }

      &:disabled,
      &.disabled {
        background: $color linear-gradient(180deg, mix($body-bg, $color, 15%), $color) repeat-x !important;
        background-image: none !important;
        color: color-yiq($color);
      }
    }
  }
}
```

I have tried using:

```scss
&:hover:not(:disabled):not(.disabled) {
  background: $color linear-gradient(180deg, mix($body-bg, darken($color, 7.5%), 15%), darken($color, 7.5%)) repeat-x !important;
  border-color: darken($color, 10%);
  color: darken(color-yiq($color), 7.5%);
}
```

But that did not work because there is a `.btn:hover` style from bootstrap that changes the color and/or the background color. So I'm not sure if there is any other alternative to fix this...

2021-05-16 01:44 UTC, danny007in commented on build/scss/mixins/_backgrounds.scss
> +        background: $color linear-gradient(180deg, mix($body-bg, $color, 15%), $color) repeat-x !important;
@Shidersz just fix this, 
then 
once ill check 
and merge it.

2021-05-16 15:26 UTC, Shidersz commented on build/scss/mixins/_backgrounds.scss
> +        background: $color linear-gradient(180deg, mix($body-bg, $color, 15%), $color) repeat-x !important;
Ok, I have made some changes to remove `background` property and get it work...

2021-06-12 01:28 UTC, REJack commented
The changes looks good, only one point:

the font color on gradient buttons changes on hover.
![grafik](https://user-images.githubusercontent.com/1554582/121761025-efad2200-cb2d-11eb-8664-8e5e0e26b503.png)
![grafik](https://user-images.githubusercontent.com/1554582/121761034-fb98e400-cb2d-11eb-8c3b-fe196664a9e6.png)

2021-06-12 01:39 UTC, Shidersz commented
@REJack I will check that when I get some time...

2021-06-12 15:20 UTC, Shidersz commented
@REJack I have upload a fix for that, please check again...

2021-06-12 16:56 UTC, REJack commented
perfect 👍🏻

2021-06-12 16:56 UTC, merged