Fix Using / for division is deprecated
ColorlibHQ/AdminLTE pull request #4123
Opened 2021-12-12 14:50 UTC by forxer

This PR intend to solve #4015

2021-12-12 15:32 UTC, danny007in requested changes

2021-12-12 15:32 UTC, danny007in commented on build/scss/plugins/_select2.scss
> +        margin-top: -divide($input-padding-x-sm, 5);
fix this `-divide(`

2021-12-12 21:13 UTC, forxer commented on build/scss/plugins/_select2.scss
> +        margin-top: -divide($input-padding-x-sm, 5);
I'm not sure what I need to fix this is working for me. Can you tell me more? I would be happy to correct it.

2021-12-13 07:43 UTC, forxer commented on build/scss/plugins/_select2.scss
> +        margin-top: -divide($input-padding-x-sm, 5);
ok done

2022-01-09 21:45 UTC, REJack commented
There are still bug, please fix them then I can merge it 😄

2022-01-10 09:53 UTC, forxer commented
I do not understand why the tests do not pass. I replaced :

`height: $main-header-height / 2;`

through :

`height: $main-header-height * 0.5;`

It's valid, that's what they did on [Bootstrap in this PR ](https://github.com/twbs/bootstrap/pull/34571/files)

2022-01-10 16:12 UTC, REJack commented
@danny007in do you have any clue about the errors?

2022-01-12 18:23 UTC, REJack commented
@forxer Could you enable the edit rights for maintainers? Then I would look over it tonight (CET) 😄

2022-01-18 18:35 UTC, merged