Fullscreen button
ColorlibHQ/AdminLTE pull request #5307
Opened 2023-08-29 11:09 UTC by glewe

I added a full screen button to the top menu as it was available in the BS4 version.
I saw that there is a PR for this already but it seems to be outdated.
(This is my first PR here so hopefully I did it right).
Best regards,
George

2023-08-30 08:16 UTC, danny007in commented on src/ts/fullscreen.ts
> +    const eleRequestFullscreen = document.getElementById(ID_REQUEST_FULLSCREEN_ICON)
use querySelector

2023-08-30 13:43 UTC, glewe commented on src/ts/fullscreen.ts
> +    const eleRequestFullscreen = document.getElementById(ID_REQUEST_FULLSCREEN_ICON)
Fixed in lates commit

2023-08-30 13:44 UTC, glewe commented on src/html/components/dashboard/_topbar.astro
> +          <i id="btn-request-fullscreen" class="bi bi-arrows-fullscreen"></i>
Fixed in latest commit

2023-08-30 14:34 UTC, danny007in requested changes

2023-08-30 14:34 UTC, danny007in commented on src/ts/fullscreen.ts
> +const ID_REQUEST_FULLSCREEN_ICON = '[data-lte-icon="request-fullscreen"]'
rename `ID_REQUEST_FULLSCREEN_ICON`

2023-08-30 14:34 UTC, danny007in commented on src/html/components/dashboard/_topbar.astro
> +          <i data-lte-icon="request-fullscreen" class="bi bi-arrows-fullscreen"></i>
rename as https://github.com/ColorlibHQ/AdminLTE/blob/0cb0400d8ddecb5e2ac74f9660a28de6dae16687/src/html/pages/widgets/cards.astro#L143
like `maximum`

2023-08-30 15:12 UTC, glewe commented on src/ts/fullscreen.ts
> +const ID_REQUEST_FULLSCREEN_ICON = '[data-lte-icon="request-fullscreen"]'
Makes sense. Renamed in lates commit.

2023-08-30 15:12 UTC, glewe commented on src/html/components/dashboard/_topbar.astro
> +          <i data-lte-icon="request-fullscreen" class="bi bi-arrows-fullscreen"></i>
Makes sense. Renamed in lates commit.

2023-09-01 10:57 UTC, danny007in requested changes

2023-09-01 10:57 UTC, danny007in commented on package-lock.json
remove package file, and i will merge this PR

2023-09-01 12:28 UTC, glewe commented on package-lock.json
I rolled back the changes of package-lock.json to the master branch.

2023-09-03 07:56 UTC, danny007in requested changes

2023-09-03 07:56 UTC, danny007in commented on src/ts/fullscreen.ts
> +
Add Event and dispatch

2023-09-03 08:31 UTC, glewe commented on src/ts/fullscreen.ts
> +
Done in latest commit

2023-09-10 11:15 UTC, danny007in commented
on `esc` key press, icon is not changing

https://github.com/ColorlibHQ/AdminLTE/assets/50356015/7d391b17-efca-4538-84b6-f1a92bea9a96

2023-09-12 09:03 UTC, danny007in commented
Make PR commit readable https://www.youtube.com/watch?v=gXCkYkLQ3To

2023-09-12 18:05 UTC, glewe commented
> on esc key press, icon is not changing
I added an keydown event listener to the fullscreen.ts class. However, I could not get it to change the icon on the first Esc. It takes two Esc events to change. Can you have a look?

2023-09-13 13:20 UTC, danny007in commented
@glewe 
I'm going to make some changes to the code. Please don't push anything

2023-09-13 17:27 UTC, glewe commented
> @glewe 
> I'm going to make some changes to the code. Please don't push anything

Ok. Thanks.

2023-09-14 08:58 UTC, danny007in commented
`f11` and `esc` are not stable with fullscreenmode.

once check it please. i pushed some updates

2023-09-14 09:04 UTC, merged