Bs5 Components
ColorlibHQ/AdminLTE pull request #5312
Opened 2023-08-31 09:49 UTC by glewe

The current code includes a Forms => General Elements page that show basic Bootstrap 5 form elements.
In this PR I added a Components => General Components page showing basic Bootstrap 5 elements.
(I also used this branch to fix some minor things in the form elements page.)

2023-09-01 18:57 UTC, danny007in requested changes

2023-09-01 18:57 UTC, danny007in commented on src/html/components/_scripts.astro
> +<!--end::Bootstrap Toasts-->
add this in to particular page

2023-09-01 18:57 UTC, danny007in commented on src/scss/_toasts.scss
https://getbootstrap.com/docs/5.3/components/toasts/#overview

2023-09-01 19:18 UTC, glewe commented on src/scss/_toasts.scss
Yes, that's what I use on the sample page.

2023-09-01 19:22 UTC, glewe commented
Hi @danny007in ,
I see that there was an unsuccessful check. However, I do not understand it. I ran `npm run production` and had no such error.
The error says `sass variables found` but it does not say what file and line. The only styles I added are the custom toast style. In the .scss file I did use variable like `$white` or `$red-300` but those are used in the other .scss files as well.
Can you help me out here and tell me what I did wrong?
Thanks and best regards,
George

2023-09-02 09:21 UTC, danny007in commented
> Hi @danny007in , I see that there was an unsuccessful check. However, I do not understand it. I ran `npm run production` and had no such error. The error says `sass variables found` but it does not say what file and line. The only styles I added are the custom toast style. In the .scss file I did use variable like `$white` or `$red-300` but those are used in the other .scss files as well. Can you help me out here and tell me what I did wrong? Thanks and best regards, George

https://github.com/twbs/bootstrap/pull/38283 please check

2023-09-02 09:38 UTC, danny007in commented on src/scss/_toasts.scss
https://getbootstrap.com/docs/5.3/components/toasts/#variables

use this variable in custom class it will organized also add in loop

```scss
--#{$prefix}toast-color: #{$toast-color};
--#{$prefix}toast-bg: #{$toast-background-color};
--#{$prefix}toast-border-color: #{$toast-border-color};
--#{$prefix}toast-box-shadow: #{$toast-box-shadow};
--#{$prefix}toast-header-color: #{$toast-header-color};
--#{$prefix}toast-header-bg: #{$toast-header-background-color};
--#{$prefix}toast-header-border-color: #{$toast-header-border-color};

2023-09-02 09:47 UTC, danny007in requested changes

2023-09-02 09:47 UTC, danny007in commented on src/html/components/_scripts.astro
> +<!--begin::Bootstrap Tooltips-->
move this Bootstrap Tooltips js script that particular page

2023-09-02 09:47 UTC, danny007in commented on src/html/pages/components/general.astro
move this page to `src/html/pages/forms/advance.astro` also please split as https://adminlte.io/themes/v3/

2023-09-02 09:47 UTC, danny007in commented on src/scss/adminlte.scss
> +@import "toasts";
move to `src\scss\parts\_extra-components.scss`

2023-09-02 09:47 UTC, danny007in commented on src/html/pages/forms/general.astro
> +                <div class="card card-warning card-outline mb-2">
use `mb-4` for bottom space

2023-09-03 14:46 UTC, glewe commented on src/scss/_toasts.scss
Updated. Saved a bunch of lines even.

2023-09-03 14:52 UTC, glewe commented on src/html/components/_scripts.astro
> +<!--begin::Bootstrap Tooltips-->
This suggestion I would ask you to reconsider. Tooltips are a basic feature often used on many pages of a site. I feel it does not make sense to put the same code on each page. I think it is at the right spot here like the toast checks. It gives a developer the freedom to use tooltips anywhere without considering addl. Javascript. They work right away.
What do think?

2023-09-03 14:58 UTC, glewe commented on src/html/pages/components/general.astro
Since these are rather general UI elements, what do you think about putting the page as "General Elements" under UI Elements (`src/html/pages/UI/general.astro`)?

2023-09-03 15:45 UTC, glewe commented on src/scss/adminlte.scss
> +@import "toasts";
Done

2023-09-03 15:48 UTC, glewe commented on src/html/pages/forms/general.astro
> +                <div class="card card-warning card-outline mb-2">
Done

2023-09-05 11:12 UTC, danny007in requested changes

2023-09-05 11:12 UTC, danny007in commented on src/scss/_toasts.scss
> +  --#{$prefix}toast-color: #{$black};
https://github.com/ColorlibHQ/AdminLTE/blob/65a59ed6683fc799fbaad443e315e53df8ca10ca/src/scss/_direct-chat.scss#L225

looping it more efficient

2023-09-05 11:15 UTC, danny007in commented on src/html/components/_scripts.astro
> +<!--begin::Bootstrap Tooltips-->
can move here https://github.com/ColorlibHQ/AdminLTE/tree/master/src/ts

2023-09-05 16:43 UTC, glewe commented
I added the Bootstrap color loop into _toasts.scss. Never did that before. I had to add a function though to get the subtle bg color. Is there any easier way (e.g. build a variable from a variable)?

2023-09-05 17:01 UTC, glewe commented on src/html/components/_scripts.astro
> +<!--begin::Bootstrap Tooltips-->
I do not understand what you mean here. How do I move the scripts to another location?

2023-09-05 17:20 UTC, glewe commented on src/html/pages/components/general.astro
I moved the general BS components page under 'UI Elements'

2023-09-05 17:27 UTC, danny007in requested changes

2023-09-05 17:27 UTC, danny007in commented on src/scss/_toasts.scss
> +  //--#{$prefix}toast-color: #{$black};
remove comments

2023-09-05 17:27 UTC, danny007in commented on src/scss/_toasts.scss
> +//.toast-danger {
remove comments

2023-09-05 17:27 UTC, danny007in commented on src/scss/_toasts.scss
>    --#{$prefix}toast-border-radius: 0 0 .25rem .25rem;
default radius?

2023-09-05 17:34 UTC, danny007in requested changes
![image](https://github.com/ColorlibHQ/AdminLTE/assets/50356015/d4aff756-74f4-4ceb-93be-858ed4c74950)

2023-09-05 18:03 UTC, glewe commented on src/scss/_toasts.scss
> +  --#{$prefix}toast-color: #{$black};
Done

2023-09-05 18:03 UTC, glewe commented on src/scss/_toasts.scss
> +  //--#{$prefix}toast-color: #{$black};
Done

2023-09-05 18:04 UTC, glewe commented on src/scss/_toasts.scss
> +//.toast-danger {
Done

2023-09-05 18:10 UTC, glewe commented on src/scss/_toasts.scss
>    --#{$prefix}toast-border-radius: 0 0 .25rem .25rem;
Indeed. The extra border-radius is not necessary. When I started I saw no radius at the toast bottom. Not sure why.
I removed that now.

2023-09-05 18:59 UTC, glewe commented
> Close button color-contrast !
That was a bit tricky because the close button x is a hard coded black SVG URL. Text color style doesn't to anything to it. I added a function to _toasts.scss that either creates a white or a black SVG based on the given color.

2023-09-10 12:20 UTC, danny007in commented on src/html/components/_scripts.astro
> +<!--begin::Bootstrap Tooltips-->
move js to particular file, so there will be clarity to user they this code is here

2023-09-10 12:24 UTC, danny007in commented on src/scss/_toasts.scss
> +    --#{$prefix}toast-bg: #{get-subtle-bg-color($name)};
for subtle color try this method

[--#{$prefix}alert-bg: var(--#{$prefix}#{$state}-bg-subtle);](https://github.com/twbs/bootstrap/blob/413894d4691b5ebb1377fcf5ab8fd3bba49766a8/scss/_alert.scss#L63)

2023-09-12 09:04 UTC, danny007in commented
Make PR commit readable https://www.youtube.com/watch?v=gXCkYkLQ3To

2023-09-12 16:33 UTC, glewe commented on src/scss/_toasts.scss
> +    --#{$prefix}toast-bg: #{get-subtle-bg-color($name)};
Indeed, that works fine. Thanks.

2023-09-12 16:38 UTC, glewe commented
https://github.com/ColorlibHQ/AdminLTE/pull/5312#discussion_r1320759794

Sorry, but I don't know how or maybe I am misunderstanding. How do create a separate JS file and make sure it ends up in the `dist/js` folder when building the site? Then I could reference it as:
```
<!--begin::Bootstrap Toasts-->
<script src="js/bs-toasts.js" is:inline></script>
<!--end::Bootstrap Toasts-->
```

2023-09-13 10:39 UTC, danny007in commented
@glewe I'm going to make some changes to the code. Please don't push anything

2023-09-13 10:42 UTC, glewe commented
Ok. Thanks.

2023-09-13 12:42 UTC, danny007in commented
In dark mode toast is not good, any idea @glewe 

![image](https://github.com/ColorlibHQ/AdminLTE/assets/50356015/4d0324a7-4f45-4324-86d6-c1ab7d9ea674)

2023-09-13 16:12 UTC, glewe commented
> In dark mode toast is not good, any idea @glewe
> 
I think the colors are ok. They match the BS colors. The only thing that does not work well is the filter for the close button SVG. Therefore, the following lines should be added to the `_toasts.scss` file:
```
[data-bs-theme="dark"] .btn-close {
  filter: none !important;
}
```

2023-09-13 16:32 UTC, danny007in commented
> > In dark mode toast is not good, any idea @glewe
> 
> I think the colors are ok. They match the BS colors. The only thing that does not work well is the filter for the close button SVG. Therefore, the following lines should be added to the `_toasts.scss` file:
> 
> ```
> [data-bs-theme="dark"] .btn-close {
>   filter: none !important;
> }
> ```

can make changes now 👍🏼

2023-09-13 16:37 UTC, glewe commented
> I have pushed some code @glewe

Thanks. I pulled your changes and updated my local branch.

2023-09-14 12:19 UTC, danny007in commented
pushed code, please upstream

2023-09-14 12:25 UTC, danny007in approved these changes

2023-09-14 12:26 UTC, merged