Local Google Fonts
ColorlibHQ/AdminLTE pull request #5313
Opened 2023-09-01 19:09 UTC by glewe

This was a feature request #5296
I also ran into cases where I had to switch to local Google fonts due to European GDPR laws (loading fonts from Google transfers the user's IP address to Google without his consent).

The currently used font Source Sans Pro has been updated and is now named "Source Sans 3". I downloaded the woff2 files for weights 300, 400 and 700 (normal and italic) in cyrillic, cyrillic-ext, greek, greek-ext, latin, latin-ext and vietnamese versions (as the remote CSS from Google fonts currently provides).

I left the reference to the remote Google fonts in `_head.astro` in case someone wants to use those. However, in that case the user also needs to remove the references to the local font files and re-compile adminlte.css.

2023-09-02 09:09 UTC, danny007in commented
is there any cdn option?

2023-09-03 15:56 UTC, glewe commented
> 

Any option with accessing resources from a remote source before the user gives his consent is legally not allowed. The reason behind this is that a remote service can read and use the requesting IP address which is part of the user's identity. In the case of Google fonts there were quite a lot of law suites last year in Europe, specifically in Germany. This lead for example to the development of the OMGF WordPress plugin that allows to host the used Google fonts locally.

2023-09-11 15:13 UTC, danny007in commented
Can we use this

https://www.jsdelivr.com/package/npm/source-sans-pro

2023-09-14 12:43 UTC, glewe commented
> After running the `npm run production` command, will this work? I would prefer to use only CDNs so that users can choose their own fonts.

Indeed, `npm run production` does not work with the node_modules version (npm run dev does). It cannot find the .css file so it says. 
So I switched to the CDN of Source Sans Pro as you suggested. I assume that is acceptable from a GDPR perspective since I have never heard of that case being a problem.
I also see your point of making it easier for users to select a different font.

2023-09-14 13:13 UTC, danny007in requested changes

2023-09-14 13:13 UTC, danny007in commented on src/assets/fonts/SourceSans3/SourceSans3-Light-cyrillic-ext.woff2
remove unwanted files

2023-09-14 13:13 UTC, danny007in commented on src/html/components/_head.astro
> +  href=" https://cdn.jsdelivr.net/npm/source-sans-pro@3.6.0/source-sans-pro.min.css "
Please visit https://www.jsdelivr.com/package/npm/@fontsource/source-sans-3?tab=files

![image](https://github.com/ColorlibHQ/AdminLTE/assets/50356015/fb8ed32c-9d60-47eb-aaf7-412545f6484f)

2023-09-14 17:00 UTC, glewe commented on src/assets/fonts/SourceSans3/SourceSans3-Light-cyrillic-ext.woff2
Oops, my bad. Now removed.

2023-09-14 17:01 UTC, glewe commented on src/html/components/_head.astro
> +  href=" https://cdn.jsdelivr.net/npm/source-sans-pro@3.6.0/source-sans-pro.min.css "
Yes, that is another option. I switched to Source Sans 3 from fontsource.

2023-09-16 10:09 UTC, danny007in commented
I'm going to make some changes to the code. Please don't push anything

2023-09-16 10:22 UTC, merged